services:
  autoeval-dev:
    build:
      context: .
      target: dev
    image: autoeval-dev:latest
    volumes:
      - ./src:/app/src
      - ./inputs:/app/inputs # batch STAC item run lists go here
      - ./tools:/app/tools
      - ./data:/data # for output data when outputting data locally
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    entrypoint: [ sleep, infinity ]
    network_mode: host
